name: Build Golang Bot Covid-19

on:
  release:
    types: [published]

jobs:

  build:

    strategy:
        matrix:
          go-version: [1.14.x]
          platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10}
    - name: Build the tagged Docker image
      run: docker build --tag docker.pkg.github.com/k1m0ch1/covid-19-api/gobot-covid:${{steps.vars.outputs.tag}} -f src/gobot-covid/Dockerfile src/gobot-covid/.
    - name: Push the tagged Docker image
      run: docker push docker.pkg.github.com/k1m0ch1/covid-19-api/gobot-covid:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build --tag docker.pkg.github.com/k1m0ch1/covid-19-api/gobot-covid:latest -f src/gobot-covid/Dockerfile src/gobot-covid/.
    - name: Push the latest Docker image
      run: docker push docker.pkg.github.com/k1m0ch1/covid-19-api/gobot-covid:latest
