name: Testing Action

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
          python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Just hello
      run: echo "hello"
